### ISSUE TITLE
Add an Open in Colab badge

### ISSUE THREAD

**Issue by sgbaird** [cseeg/DiSCoVeR-SuperCon-NOMAD-SMACT#2]
See https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb

Can be added to both the README and the notebook

**Comment by sgbaird** [comment]
@cseeg you should still have the notebook in GitHub. Did you see this from the link above?

![image](https://user-images.githubusercontent.com/45469701/183786245-f7f05301-0f17-4b8a-954e-a6290669ceff.png)

Notice how the link `https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb` is pulling directly from a GitHub repository:
https://github.com/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb
and that it has an "Open in Colab" badge at the top (which you can add to both the README and the notebook).

**Comment by sgbaird** [comment]
Also, you haven't opened up permissions on the notebook:
![image](https://user-images.githubusercontent.com/45469701/183786666-3ba9d4e4-fd35-415a-92c6-04f2f29fd0be.png)

**Comment by sgbaird** [comment]
See https://www.screencast.com/t/d5cpFRGrpUlc for a quick demo of how you can save it to GitHub with an "Open in Colab" link beginning from you having it open in Colab on your machine. I.e. you can save it to GitHub directly from Colab and have it add the badge for you automatically.

**Comment by cseeg** [comment]
The colab badge should be good now and giving access, let me know if it works now @sgbaird

**Comment by sgbaird** [comment]
I can open it now 👍
